2021-02-18 13:41:11,180 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6NywiZXhwIjoxNjEzNjM2NDQxLjExNDMxNTd9.KzOGZQg55hGUHgOz5wJNp9djey46T9nMx_IBOB6Gdy0 [GET] [in /home/ashutosh.mahawar/.local/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/ashutosh.mahawar/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ashutosh.mahawar/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ashutosh.mahawar/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ashutosh.mahawar/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ashutosh.mahawar/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ashutosh.mahawar/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ashutosh.mahawar/flaskprojects/application1/app/routes.py", line 190, in reset_password
    return render_template('reset_password.html', form=form)
  File "/home/ashutosh.mahawar/.local/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/ashutosh.mahawar/.local/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/ashutosh.mahawar/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/ashutosh.mahawar/.local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/ashutosh.mahawar/.local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/ashutosh.mahawar/flaskprojects/application1/app/templates/reset_password.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/ashutosh.mahawar/flaskprojects/application1/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/home/ashutosh.mahawar/flaskprojects/application1/app/templates/reset_password.html", line 8, in block "content"
    {{ form.password.label }}<br>
  File "/home/ashutosh.mahawar/.local/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.ResetPasswordRequestForm object' has no attribute 'password'
2021-02-18 13:43:16,189 INFO: Application startup [in /home/ashutosh.mahawar/flaskprojects/application1/app/__init__.py:49]
2021-02-18 13:44:28,256 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6NywiZXhwIjoxNjEzNjM2NjA2LjAwNzgwNzV9.Sny4u36nQA5SEAK4lSkJ62uMrvJ8_Bjm7i6Q4wxF65E [GET] [in /home/ashutosh.mahawar/.local/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/ashutosh.mahawar/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ashutosh.mahawar/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ashutosh.mahawar/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ashutosh.mahawar/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ashutosh.mahawar/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ashutosh.mahawar/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ashutosh.mahawar/flaskprojects/application1/app/routes.py", line 190, in reset_password
    return render_template('reset_password.html', form=form)
  File "/home/ashutosh.mahawar/.local/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/ashutosh.mahawar/.local/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/ashutosh.mahawar/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/ashutosh.mahawar/.local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/ashutosh.mahawar/.local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/ashutosh.mahawar/flaskprojects/application1/app/templates/reset_password.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/ashutosh.mahawar/flaskprojects/application1/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/home/ashutosh.mahawar/flaskprojects/application1/app/templates/reset_password.html", line 8, in block "content"
    {{ form.password.label }}<br>
  File "/home/ashutosh.mahawar/.local/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.ResetPasswordRequestForm object' has no attribute 'password'
2021-02-18 13:53:22,293 INFO: Application startup [in /home/ashutosh.mahawar/flaskprojects/application1/app/__init__.py:49]
